# ==============================================================================
# Data Variables
# ==============================================================================

variable "project_resource_group_name" {
  type        = string
  description = "(Required) The name of the Resource Group in which the subnet should be exist. Changing this forces a new resource to be created."
}


variable "subnet_virtual_network_name" {
  type        = string
  description = "(Required) The name of the virtual network to which to attach the subnet. Changing this forces a new resource to be created."
}

# ==============================================================================
# Subnet Variables
# ==============================================================================
variable "resource_deploy" {
  type        = bool
  description = "Set to true if resource should be deployed ; set it to false if not ; true is the default value"
  default     = true
}
variable "resource_depends_on" {
  type    = any
  default = null
}
variable "subnet_name" {
  type        = string
  description = "(Required) The name of the subnet. Changing this forces a new resource to be created."
}
variable "subnet_address_prefix" {
  type        = list(string)
  description = "(Required) The address prefix to use for the subnet."
  default     = []
}
# variable "subnet_address_prefix" {
#   type        = string
#   description = "(Required) The address prefix to use for the subnet."
#   default     = ""
# }
variable "subnet_enforce_private_link_endpoint_network_policies" {
  type        = bool
  description = "(Optional) Enable or Disable network policies for the private link endpoint on the subnet."
  default     = false
}
variable "subnet_enforce_private_link_service_network_policies" {
  type        = bool
  description = "(Optional) Enable or Disable network policies for the private link service on the subnet. ."
  default     = false
}
variable "subnet_service_endpoints" {
  type        = list(string)
  description = "(Optional) The list of Service endpoints to associate with the subnet."
  default     = []
}

variable "subnet_service_delegations" {
  description = "(Optional) One or more delegation blocks as defined below."
  type = list(object({
    name = string
    service_delegation = object({
      name    = string            //   
      actions = list(string)      //
    })

  }))
  default = []
}

# variable "subnet_delegations_actions" {
#   type    = map(list(string))
#   default     = []
#   # default = {
#   #   "Microsoft.Web/serverFarms"                       = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.ContainerInstance/containerGroups"     = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.Netapp/volumes"                        = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.HardwareSecurityModules/dedicatedHSMs" = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.ServiceFabricMesh/networks"            = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.Logic/integrationServiceEnvironments"  = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.Batch/batchAccounts"                   = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.Sql/managedInstances"                  = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
#   #   "Microsoft.Web/hostingEnvironments"               = ["Microsoft.Network/virtualNetworks/subnets/action"]
#   #   "Microsoft.BareMetal/CrayServers"                 = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.Databricks/workspaces"                 = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action", "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"]
#   #   "Microsoft.BareMetal/AzureVMware"                 = ["Microsoft.Network/networkinterfaces/*", "Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.StreamAnalytics/streamingJobs"         = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.DBforPostgreSQL/serversv2"             = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
#   #   "Microsoft.AzureCosmosDB/clusters"                = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
#   # }
# }


# variable "aks_diagnostics_logs_map" {
#   description = "(Optional) Send the logs generated by AKS master node to diagnostics"
#   default = {
#     log = [
#       #["Category name",  "Diagnostics Enabled", "Retention Enabled", Retention period] 
#       ["kube-apiserver", true, true, 30],
#       ["kube-controller-manager", true, true, 30],
#       ["kube-scheduler", true, true, 30],
#       ["kube-audit", true, true, 30],
#       ["cluster-autoscaler", true, true, 30]
#     ]
#     metric = [
#       ["AllMetrics", true, true, 30],
#     ]
#   }
# }
