# ======================================================
# Creates TLS Private Key
# ======================================================

// Important Security Notice 
// The private key generated by this resource will be stored unencrypted in your Terraform state file. 
// Use of this resource for production deployments is not recommended. 
//
// Instead, generate a private key file outside of Terraform and distribute it securely 
// to the system where Terraform will be run.

// more info here for the best practices to implement :
// https://docs.microsoft.com/en-us/azure/aks/ssh

resource "tls_private_key" "ssh" {
  count       = (var.resource_deploy ? 1 : 0)
  algorithm   = var.ssh_algorithm
  ecdsa_curve = var.ssh_ecdsa_curve
  rsa_bits    = var.ssh_rsa_bits
}

# resource "local_file" "private_key" {
#   count    = var.public_ssh_key == "" ? 1 : 0
#   content  = tls_private_key.ssh.private_key_pem
#   filename = var.private_key_filename
# }